wtyicy:
  # 文件存储地址 默认 wtyicy
  filePath: wtyicy
  # 默认上传云端  默认 qiniuyun
  defaultType:
  # ===================================================================
  # 阿里云对象存储
  # ===================================================================
  aliyun:
    # 上传地址
    endpoint:
    # ID
    accessKeyId:
    # 密钥
    accessKeySecret:
    # 存储桶
    bucketName:
    # 访问地址
    url:
  # ===================================================================
  # 七牛云对象存储
  # ===================================================================
  qiniuyun:
    # 存储和访问地址
    endpoint:
    # Id
    accessKeyId:
    # 密钥
    accessKeySecret:
    # 存储桶
    bucketName:
  # ===================================================================
  # 分布式文件系统FDFS配置
  # ===================================================================
  fdfs:
    # 访问地址
    url:
    # 上传地址
    trackerList:
      -
  # ===================================================================
  # 腾讯云对象存储
  # ===================================================================
  qcloudyun:
    # ID
    accessKeyId:
    # 密钥
    accessKeySecret:
    # 上传区域地点
    bucket:
    # 存储桶
    bucketName:
    # 访问地址
    url:
  # ===================================================================
  # 百度云对象存储
  # ===================================================================
  baiduyun:
    # Id
    accessKeyId:
    # 密钥
    accessKeySecret:
    # 存储桶
    bucketName:
    # 访问地址
    url:
    # 上传地址
    endpoint:
  # ===================================================================
  # 华为云对象存储
  # ===================================================================
  huaweiyun:
    # Id
    accessKeyId:
    # 密钥
    accessKeySecret:
    # 存储桶
    bucketName:
    # 访问地址
    url:
    # 上传地址
    endpoint:
  # ===================================================================
  # 京东云对象存储
  # ===================================================================
  jingdongyun:
    # Id
    accessKeyId:
    # 密钥
    accessKeySecret:
    # 存储桶
    bucketName:
    # 上传区域地点
    bucket:
    # 访问地址
    url:
    # 上传地址
    endpoint:
